name: Deploy PHP App to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Nginx
      run: |
        sudo cp -r . /var/www/html/
        sudo chown -R root:root /var/www/html/index.php
        sudo chmod -R 755 /var/www/html/index.php

    - name: nginx restart
      run: sudo systemctl restart nginx

