name: Deploy application

on:
  push:
    branches: [ dev, stage, production ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: 

