name: Deployment

on:
  push:
    branches: [dev, stage, production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set environment on branch
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "env=DEV" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            echo "env=STAGE" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "env=PROD" >> $GITHUB_OUTPUT
          fi

      - name: Upload files 
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets[format('{0}_SERVER_IP', steps.set-env.outputs.env)] }}
          username: ${{ secrets[format('{0}_SERVER_USER', steps.set-env.outputs.env)] }}
          key: ${{ secrets[format('{0}_SSH_KEY', steps.set-env.outputs.env)] }}
          source: "."
          target: "/home/ubuntu/app"

      - name: Restart Apache
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets[format('{0}_SERVER_IP', steps.set-env.outputs.env)] }}
          username: ${{ secrets[format('{0}_SERVER_USER', steps.set-env.outputs.env)] }}
          key: ${{ secrets[format('{0}_SSH_KEY', steps.set-env.outputs.env)] }}
          script: |
          
            sudo mv /home/ubuntu/app/* /var/www/html
            sudo systemctl restart apache2
